### ISSUE TITLE
'bin_label' is undefined when i want to evaluate exeter/claim_binary

### ISSUE THREAD

**Issue by airaer1998** [eci-io/climategpt-evaluation#2]
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/lm_eval/__main__.py", line 417, in <module>
    cli_evaluate()
  File "/usr/local/lib/python3.8/dist-packages/lm_eval/__main__.py", line 342, in cli_evaluate
    results = evaluator.simple_evaluate(
  File "/usr/local/lib/python3.8/dist-packages/lm_eval/utils.py", line 288, in _wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lm_eval/evaluator.py", line 192, in simple_evaluate
    task_dict = get_task_dict(tasks, task_manager)
  File "/usr/local/lib/python3.8/dist-packages/lm_eval/tasks/__init__.py", line 420, in get_task_dict
    task_name_from_string_dict = task_manager.load_task_or_group(
  File "/usr/local/lib/python3.8/dist-packages/lm_eval/tasks/__init__.py", line 270, in load_task_or_group
    collections.ChainMap(*map(self._load_individual_task_or_group, task_list))
  File "/usr/local/lib/python3.8/dist-packages/lm_eval/tasks/__init__.py", line 161, in _load_individual_task_or_group
    return load_task(task_config, task=name_or_config, group=parent_name)
  File "/usr/local/lib/python3.8/dist-packages/lm_eval/tasks/__init__.py", line 150, in load_task
    task_object = ConfigurableTask(config=config)
  File "/usr/local/lib/python3.8/dist-packages/lm_eval/api/task.py", line 825, in __init__
    test_target = self.doc_to_target(test_doc)
  File "/usr/local/lib/python3.8/dist-packages/lm_eval/api/task.py", line 1061, in doc_to_target
    target_string = utils.apply_template(doc_to_target, doc)
  File "/usr/local/lib/python3.8/dist-packages/lm_eval/utils.py", line 371, in apply_template
    return rtemplate.render(**doc)
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
jinja2.exceptions.UndefinedError: 'bin_label' is undefined

**Comment by Castrol68** [comment]
> Traceback (most recent call last): File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.8/runpy.py", line 87, in _run_code exec(code, run_globals) File "/usr/local/lib/python3.8/dist-packages/lm_eval/**main**.py", line 417, in cli_evaluate() File "/usr/local/lib/python3.8/dist-packages/lm_eval/**main**.py", line 342, in cli_evaluate results = evaluator.simple_evaluate( File "/usr/local/lib/python3.8/dist-packages/lm_eval/utils.py", line 288, in _wrapper return fn(*args, **kwargs) File "/usr/local/lib/python3.8/dist-packages/lm_eval/evaluator.py", line 192, in simple_evaluate task_dict = get_task_dict(tasks, task_manager) File "/usr/local/lib/python3.8/dist-packages/lm_eval/tasks/**init**.py", line 420, in get_task_dict task_name_from_string_dict = task_manager.load_task_or_group( File "/usr/local/lib/python3.8/dist-packages/lm_eval/tasks/**init**.py", line 270, in load_task_or_group collections.ChainMap(*map(self._load_individual_task_or_group, task_list)) File "/usr/local/lib/python3.8/dist-packages/lm_eval/tasks/**init**.py", line 161, in _load_individual_task_or_group return load_task(task_config, task=name_or_config, group=parent_name) File "/usr/local/lib/python3.8/dist-packages/lm_eval/tasks/**init**.py", line 150, in load_task task_object = ConfigurableTask(config=config) File "/usr/local/lib/python3.8/dist-packages/lm_eval/api/task.py", line 825, in **init** test_target = self.doc_to_target(test_doc) File "/usr/local/lib/python3.8/dist-packages/lm_eval/api/task.py", line 1061, in doc_to_target target_string = utils.apply_template(doc_to_target, doc) File "/usr/local/lib/python3.8/dist-packages/lm_eval/utils.py", line 371, in apply_template return rtemplate.render(**doc) File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1301, in render self.environment.handle_exception() File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 936, in handle_exception raise rewrite_traceback_stack(source=source) File "", line 1, in top-level template code jinja2.exceptions.UndefinedError: 'bin_label' is undefined

I meet a same problem, could you please tell me how to deal with it?
